name: CI                                                            # Suggestiongs:
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:                                                        # delete
  # Skip intermediate builds: always.                               # delete
  # Cancel intermediate builds: only if it is a pull request build. # delete
  group: ${{ github.workflow }}-${{ github.ref }}                   # delete
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}   # delete
jobs:
  test: # Job to run test suite
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60                                             # delete
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created # delete
      actions: write                                                # delete
      contents: read                                                # delete
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.6'
          - 'pre'                                                   # - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2                                # delete - replace below
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1

       
#       - uses: actions/cache@v1
#         env:
#           cache-name: cache-artifacts
#         with:
#           path: ~/.julia/artifacts
#           key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
#           restore-keys: |
#             ${{ runner.os }}-test-${{ env.cache-name }}-
#             ${{ runner.os }}-test-
#             ${{ runner.os }}-


#       - uses: julia-actions/julia-processcoverage@v1
#       - uses: codecov/codecov-action@v3
#         with:
#           file: lcov.info